### ISSUE TITLE
Feature Request: Instance-specific loot rules

### ISSUE THREAD

**Issue by Jakobud** [Sulpitz/SmartLoot#2]
This addon works great. It would be nice though if you could setup different loot rules for different dungeons. For example, in AQ20 you might want to always roll need on all Idols and Scarabs. But in AQ40 you want to pass on all of those items. You can't easily or quickly switch between these things in the interface. Would be cool if you could set it up so that in dungeon A the rules are X and dungeon B, the rules are Y.

**Comment by Jakobud** [comment]
An alternative to this would be to implement Ace3 profiles so that you could simply switch between them depending on the raid you are in.

**Comment by Sulpitz** [comment]
Hey,
All i wanted to do is port this awesome addon from the vanill 1.12.2 version to Classic. I have no additional features planed.
