### ISSUE TITLE
Available for adoption

### ISSUE THREAD

**Issue by lareeth** [Sulpitz/SmartLoot#3]
Hi, is this available for adoption? As I'm keen to maintain for TBC

**Comment by Sulpitz** [comment]
Hi,
I just updated it to work in TBC. Should be all fixed now. 
Thanks for offering you help. Would you just want to maintain it, or also develop new Features?

**Comment by lareeth** [comment]
It was just to maintain and ensure it works release to release, but as you updated for TBC, there's nothing for me to do 😄
